### ISSUE TITLE
Unable to create border around image or figure

### ISSUE THREAD

**Issue by anthonybrandon** [rst2pdf/rst2pdf#1016]
**Description of problem**

I found https://github.com/rst2pdf/rst2pdf/issues/138 explaining that it should be possible to create a border around a figure.
I tried the solutions proposed there but am unable to get it tor work. I am using 
The last comment proposed there to use the BOX command does actually create a box, but it is as wide as the page instead of the figure.

I tried the following stylesheet:

```yaml
styles:
  with-border:
    backColor: white
    borderColor: black
    borderWidth: 1
    borderPadding: 8
    parent: figure
  figure:
      commands: []
          [ "BOX", [ 0, 0 ], [ -1, -1 ], 0.25, "black" ]
```

rst code is as follows:

```
.. class:: with-border
.. figure:: image.png
   :scale: 100%
```

**What is the expected output? What do you see instead?**

I expect a box around a figure, and see either no box (when using above `with-border style`), or a box as wide as the entire page (when using the figure style).

🖥 **Versions**

`python -V`

Python 3.8.10

`pip freeze | grep rst2pdf`

rst2pdf==0.98

`pip freeze | grep reportlab`

reportlab==3.5.68

Which operating system are you using?

Mint.

**Comment by lornajane** [comment]
Thanks for the clear bug report, I think I do understand the problem but I'm not exactly sure what the solution would be. Could you try with `image` rather than `figure`? We've seen a few other bugs about the way figure is implemented and it's a different level of block than the image is.

**Comment by anthonybrandon** [comment]
Hi, thanks for helping with this. I've tried changing to:

```yaml
styles:
  with-border:
    backColor: white
    borderColor: black
    borderWidth: 1
    borderPadding: 8
    parent: image
```
with:
```
.. class:: with-border
.. image:: image.png
   :scale: 100%
```
But this results in no border.
The same is true for:
```yaml
styles:
  image:
      commands: []
          [ "BOX", [ 0, 0 ], [ -1, -1 ], 0.25, "black" ]
```
with
```
.. image:: image.png
   :scale: 100%
```

**Comment by akrabat** [comment]
Interestingly, we have a test for this: `test_issue_138`.

[This](https://github.com/rst2pdf/rst2pdf/blob/master/rst2pdf/tests/input/test_issue_138.rst) is the rst:

```rst
This is the default figure class:

.. figure:: images/title.png

   This is the caption.

   And this is the legend.

This is a figure with ``with-border`` class:

.. class:: with-border
.. figure:: images/title.png

   This is the caption.

   And this is the legend.
```

With this style:

```yaml
styles:
  with-border:
    backColor: white
    borderPadding: 8
    commands:
    - - BOX
      - - 0
        - 0
      - - -1
        - -1
      - 0.25
      - black
    - - VALIGN
      - - 0
        - 0
      - - -1
        - -1
      - TOP
    - - ALIGN
      - - 0
        - 0
      - - -1
        - -1
      - CENTER
    parent: figure
```

Expected output is this PDF: https://github.com/rst2pdf/rst2pdf/blob/master/rst2pdf/tests/reference/test_issue_138.pdf

**Comment by akrabat** [comment]
Note that a "neater" YAML formatting of that style file would be:

```yaml
styles:
  with-border:
    parent: figure
    backColor: white
    borderPadding: 8
    commands:
    - [BOX, [0, 0], [-1, -1], 0.25, black]
    - [VALIGN, [0, 0], [-1, -1], TOP]
    - [ALIGN, [0, 0], [-1, -1], CENTER]
```

**Comment by anthonybrandon** [comment]
@akrabat Thank you. I got it to accept the yaml as follows:

```yaml
styles:
  with-border:
    parent: figure
    backColor: white
    borderPadding: 8
    commands: 
      [BOX, [0, 0], [-1, -1], 0.25, black]
      [VALIGN, [0, 0], [-1, -1], TOP]
      [ALIGN, [0, 0], [-1, -1], CENTER]
 ```

The result is quite close to what I want, except that it still spans the entire width of the page.
Is there any way to limit it to the width of the enclosed figure?
