### ISSUE TITLE
Lists (bullet, enumerable) have bad implicit before and after spacing

### ISSUE THREAD

**Issue by CendioOssman** [rst2pdf/rst2pdf#1039]
**Description of problem**

All bullet lists and enumerable lists get a weird shift downwards in the document. I.e. too much spacing above, and too little spacing below. I don't think this is intentional as it looks very odd and gives the impression that a list is related to the following paragraph.

Some crude measuring shows ~10pt between normal paragraphs, ~13pt above lists and ~7pt below lists.

**What is the expected output? What do you see instead?**

Lists should have the same spacing around them as paragraphs, but right now they have uneven spacing.

🖥 **Versions**

* Python 3.6.12
* rst2pdf 0.98
* Reportlab 3.6.1

**Additional information**

I had a look at the styles, and both `bullet-list` and `item-list` have `bodytext` as parent, so they should be getting `spaceAbove: 6`. If I override this to 0, then I get a symmetrical 7pt above and below lists.

So I tried adding the missing spacing to get things normally, and this does indeed work around the issue. I.e.:

```
    bullet-list:
      parent: bodytext
      spaceBefore: 3
      spaceAfter: 3
      commands: []
             [VALIGN, [ 0, 0 ], [ -1, -1 ], TOP ]
             [RIGHTPADDING, [ 0, 0 ], [ 1, -1 ], 0 ]
      colWidths: ["20", null]

    item-list:
      parent: bodytext
      spaceBefore: 3
      spaceAfter: 3
      commands: []
             [VALIGN, [ 0, 0 ], [ -1, -1 ], TOP ]
             [RIGHTPADDING, [ 0, 0 ], [ 1, -1 ], 0 ]
      colWidths: [20pt,null]
```

(Is there a way to override just some values from the default styles?)

You should see this on every use of lists, but as an example I tried this:

```rst
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod
tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim
veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea
commodo consequat. Duis aute irure dolor in reprehenderit in voluptate
velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint
occaecat cupidatat non proident, sunt in culpa qui officia deserunt
mollit anim id est laborum

Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod
tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim
veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea
commodo consequat. Duis aute irure dolor in reprehenderit in voluptate
velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint
occaecat cupidatat non proident, sunt in culpa qui officia deserunt
mollit anim id est laborum

1. One

2. Two

3. Three

Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod
tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim
veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea
commodo consequat. Duis aute irure dolor in reprehenderit in voluptate
velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint
occaecat cupidatat non proident, sunt in culpa qui officia deserunt
mollit anim id est laborum

* Eeny

* Meeny

* Miny

Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod
tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim
veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea
commodo consequat. Duis aute irure dolor in reprehenderit in voluptate
velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint
occaecat cupidatat non proident, sunt in culpa qui officia deserunt
mollit anim id est laborum
```
