### ISSUE TITLE
Double bulletpoints when using bulletText

### ISSUE THREAD

**Issue by zengtronic** [rst2pdf/rst2pdf#1074]
**Description of problem**
When i'm using bulletText in the Stylesheet to customize the bulletpoints it comes to a strange behavior. It places the bullettext again (but without color) under the listitem.

Is it a feature or a bug? 😄 

The used style code is following:
```
  bullet-list:
    spaceAfter: 8
    bulletText: "x" 
    bulletColor: #FF0000
```

**What is the expected output? What do you see instead?**
Expected: 
 x xyz
 x 123
 
 What I get:
![image](https://user-images.githubusercontent.com/16278720/184813851-79c372c9-860d-450f-9472-17a41a2edfce.png)

🖥 **Versions**
python: 3.7

rst2pdf: 0.99

reportlab: 3.6.5

sphinx: 3.5.4

Which operating system are you using? => Windows 11 Enterprise

**Other questions**
BTW I have also two questions where I didnt find an answer yet and probably no extra issue is needed:
- How can I disable the table header repeat on a page break? It even repeats the first table line when its a normal row (not thead)
- How can I hide an Element in rst2pdf (like display: none) in html/css

**Comment by lornajane** [comment]
That's really interesting, but probably not desired! I sometimes see the bullets on the next line, and this happens because it's actually a table layout and on some setups the "column" that the bullet points are in is too narrow and it sort of wraps. In my stylesheets I have something like this to fix the problem:

```
  bullet-list:
    colWidths: ['40', null]
    commands:
    - - VALIGN
      - [0, 0]
      - [-1, -1]
      - TOP
    - - RIGHTPADDING
      - [0, 0]
      - [1, -1]
      - 0
    - - LEFTPADDING
      - [0, 0]
      - [1, -1]
      - 6
```

Hopefully this helps!
