### ISSUE TITLE
`fontSansBold` has different defaults in different places

### ISSUE THREAD

**Issue by nkr0** [rst2pdf/rst2pdf#1220]
**Description of problem**
```rst
head
====
:author: auth

normal *italic* **bold** ``mono``
```
```sh
rst2pdf -s dejavu test.rst
pdffonts test.pdf 
```
My expectation is that, using `dejavu` built-in style sheet would use `DejaVu` fonts throughout the document. However, font used for the `fieldname` `author` is the default `Helvetica-Bold` (without embedding).

**What is the expected output? What do you see instead?**
**Expected output**
*DejaVu* fonts are found and embedded.
```
name                                 type              encoding         emb sub uni object ID
------------------------------------ ----------------- ---------------- --- --- --- ---------
AAAAAA+DejaVuSerif                   TrueType          WinAnsi          yes yes yes      6  0
AAAAAA+DejaVuSans-Bold               TrueType          WinAnsi          yes yes yes     10  0
AAAAAA+DejaVuSans                    TrueType          WinAnsi          yes yes yes     14  0
AAAAAA+DejaVuSans-Oblique            TrueType          WinAnsi          yes yes yes     18  0
AAAAAA+DejaVuSansMono                TrueType          WinAnsi          yes yes yes     22  0
```
**Actual output**
*DejaVuSans-Bold* is found. But, *Helvetica-Bold* is also used as a non-embedded font.
```
name                                 type              encoding         emb sub uni object ID
------------------------------------ ----------------- ---------------- --- --- --- ---------
AAAAAA+DejaVuSerif                   TrueType          WinAnsi          yes yes yes      7  0
Helvetica-Bold                       Type 1            WinAnsi          no  no  no       2  0
AAAAAA+DejaVuSans                    TrueType          WinAnsi          yes yes yes     11  0
AAAAAA+DejaVuSans-Oblique            TrueType          WinAnsi          yes yes yes     15  0
AAAAAA+DejaVuSans-Bold               TrueType          WinAnsi          yes yes yes     19  0
AAAAAA+DejaVuSansMono                TrueType          WinAnsi          yes yes yes     23  0
```

🖥 **Versions**
`python -V`
Python 3.11.9
`pip freeze | grep rst2pdf`
rst2pdf==0.102
`pip freeze | grep reportlab`
reportlab==4.2.0

Which operating system are you using?
Debian testing

**Additional information**
If the behaviour in code is as expected, I think changing the built-in style as below fixes the issue.
```yml
fontsAlias:
  fontSans: DejaVu Sans
  fontSansBold: DejaVu Sans Bold
  fontSansItalic: DejaVu Sans Oblique
  fontSansBoldItalic: DejaVu Sans Bold Oblique
  fontSerif: DejaVu Serif
  fontSerifBold: DejaVu Serif Bold
  fontSerifItalic: DejaVu Serif Italic
  fontSerifBoldItalic: DejaVu Serif Bold Italic
  fontMono: DejaVu Sans Mono
  fontMonoBold: DejaVu Sans Mono Bold
  fontMonoItalic: DejaVu Sans Mono Oblique
  fontMonoBoldItalic: DejaVu Sans Mono Bold Oblique
```
