### ISSUE TITLE
Background on coverPage is incorrectly used on all pages

### ISSUE THREAD

**Issue by MrMaxxan** [rst2pdf/rst2pdf#1235]
In a stylesheet I specify a background image for the cover page

```
pageSetup:
  firstTemplate: coverPage
pageTemplates:
  coverPage:
    ...
    background: source/background.png 
```

In Sphinx config I use these settings

```
extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.napoleon',
    'rst2pdf.pdfbuilder',
]

pdf_documents = [('index', u'MyLib', u'Title', u'Company'),]
pdf_stylesheets = ['sphinx', 'mystyle']
pdf_style_path = ['source/_styles']
pdf_compressed = True
pdf_use_toc = False
```

If I then generate the documentation, every page has the background. I only want it on the cover page (first page).

If pdf_use_toc is set to True, then the cover page and the contents page has the background, but the rest of the pages will correctly not have any background.

Is this a bug or how to correctly skip toc (pdf_use_toc = False) and only have the background on the first page?

Generating the PDF with sphinx-build -b pdf source build
rst2pdf version 0.102
