### ISSUE TITLE
Custom font roles have no effect

### ISSUE THREAD

**Issue by AndydeCleyre** [rst2pdf/rst2pdf#577]
Hi,

I'm having trouble making use of custom fonts throughout a document using custom roles defined in a style. Here's a simple example of what I expected to work, but results in a pdf with the standard font only.

I've got a style in my `~/.rst2pdf/styles` directory: `poetsenone.style`: 

```yaml
  styles:
    poetsenone:
      parent: bodytext
      fontName: PoetsenOne Regular
```

And I've got a sample text file: `sample_poetsenone.rst`:

```rst
.. role:: poetsenone

:poetsenone:`pack my box with five dozen liquor jugs`
```

And I generate a pdf with `rst2pdf -s poetsenone sample_poetsenone.rst`. And the resulting pdf does not feature the specified font! I am struggling to master controlling fonts with rst2pdf; any help at all is appreciated!
