### ISSUE TITLE
###Title### gets replaced to empty string

### ISSUE THREAD

**Issue by jmones** [rst2pdf/rst2pdf#652]
I'm using rst2pdf from Sphinx. I'm trying to use `###Title###` in a header by defining defaultHeader attribute in a pageTemplate. While it seems to work for `###Section###` or `###Page###`, `###Title###` is always empty.

I've checked a little bit and `doc.title` in `createpdf.HeaderOrFooter.replace.replace_tokens` seems to be empty.  Also `genelements.HandleTitle.gather_elements` never seems to get into the first if statement (`if isinstance(node.parent, docutils.nodes.document):`), which is the one I assume that should define `client.doc_title_clean` to the correct value.

I've defined the title in the `pdf_documents` definition in the `conf.py` file, which I understood it's the place to define the title of the document.

**Comment by jmones** [comment]
After digging a little bit more, a possible origin of the problem may be that everytime I get into `HandleTitle.gather_elements`, `node.parent` is of type `docutils.node.section` and not `docutils.node.document`. This is also true for the first `rst` file defined in `conf.py` in the `pdf_documents` array.

**Comment by akrabat** [comment]
Using this `.rst` file:

```rst
Test Doc
========


The Section
-----------

The content


.. raw:: pdf

    PageBreak



Another Section
---------------

Some more content
[test_header_footer_in_stylesheet.pdf]
```

and this stylesheet:

```
pageSetup:
    firstTemplate: myLayout
    margin-bottom: 8mm
    margin-left: 12mm
    margin-right: 12mm
    margin-top: 8mm

pageTemplates:
    myLayout:
        frames:  [[0cm, 0cm, 100%, 100%]]
        defaultHeader =
            Header: Section: ###Section###, Title: ###Title###, Page ###Page###
        defaultFooter =
            Footer: Section: ###Section###, Title: ###Title###, Page ###Page###
        showFooter: true
        showHeader: true
```


I get the correct information in the header and footer as seen in the attached PDF.

(https://github.com/rst2pdf/rst2pdf/files/2103864/test_header_footer_in_stylesheet.pdf)
