### ISSUE TITLE
Update manual to explain use of pyphen

### ISSUE THREAD

**Issue by akrabat** [rst2pdf/rst2pdf#888]
ReportLab supports hyphenation natively now using pyphen library along with the style settings `embeddedHyphenation` and `hyphenationLang`.

We need to document this in the manual.

These are the steps I did to test it:

Firstly, I installed pyphen with: `pip3 install pyphen`

Then:

test_hyphenation.rst:

```rst
Hyphenation Test
================

You are hereby charged that on the 28th day of May, 1970,
you did willfully, unlawfully, and with malice of forethought,
publish an alleged English-Hungarian phrase book with intent
to cause a breach of the peace. How do you plead?
```

test_hyphenation.style:

```
pageSetup:
    firstTemplate: twoColumn
    margin-left: 2cm
    margin-right: 2cm

styles:
    base:
        fontSize: 13
        leading: 15
        embeddedHyphenation: 1
        hyphenationLang: en_GB
```

Run: `rst2pdf -s test_hyphenation.style test_hyphenation.rst` to get a PDF file containing:

![Screenshot 2020-07-19 at 10 51 11](https://user-images.githubusercontent.com/33135/87872107-c59ac080-c9ad-11ea-8619-370e9564c62e.png)
