### ISSUE TITLE
fontName in style not working with fontsAlias

### ISSUE THREAD

**Issue by nfraprado** [rst2pdf/rst2pdf#902]
It seems that specifying a font as `stdFont` in `fontsAlias`, then later using `fontName: stdFont` in some style doesn't work.
Instead of using the alias it seems to be taking `stdFont` as a literal font name.

**Description of problem**

1. Download the rst and style files for "Document with Simple Styling" from the [rst2pdf examples page](https://rst2pdf.org/examples).
2. Generate the pdf
3. Change the `fontName` for the `normal` style to be literally `Georgia`
4. Regenerate the pdf
5. Notice that the font changed, even though `stdFont` should've been pointing to the `Georgia` font.

**What is the expected output? What do you see instead?**
Using `stdFont`, which is `Georgia`, or using directly `Georgia` should both yield the same pdf.

🖥 **Versions**

`python -V`: Python 3.8.5

`pip freeze | grep rst2pdf`: rst2pdf==0.97.dev0

`pip freeze | grep reportlab`: reportlab==3.5.48

**Which operating system are you using?**
Archlinux 5.8.3-arch1-1

**Additional information**

I don't actually have the Georgia font, but using `pdffonts document1-simple.pdf` (at step 2.) I can see that the font used was `DejaVuSans`, even though `fc-match Georgia` yields `DejaVu Serif`.
Using `pdffonts document1-simple.pdf` again at step 4. shows `DejaVuSerif`.
Also, `fc-match stdFont` returns `DejaVu Sans`, so that's why I think `stdFont` is being taken literally as the font name.

**Comment by lornajane** [comment]
Oh interesting. Did you install from snap/pypi/source? I haven't seen this before (we're mac/Ubuntu users) but it's not entirety dissimilar to a font thing I'm looking at already. Any more info you can share would help

**Comment by nfraprado** [comment]
I installed from the AUR (https://aur.archlinux.org/packages/rst2pdf/) which seems to install from a github release .tar.gz. Anyway, I just tested using a virtual environment and installing with pip from pypi and also from the github source (rst2pdf version 0.98), and both show the same problem.

**Comment by nfraprado** [comment]
I did some more tests, and the problem seems to be a bit more complicated than what I initially posted.
Perhaps there are multiple bugs rather than a single one.

First of all, like my initial comment, I based these tests on "Document with Simple Styling" from the examples page but I changed the fonts for ones that I have installed.
I'm testing using rst2pdf from the master branch.

1. Setting the fonts in `fontsAlias` and not using `fontName` works as expected. `stdFont` is used for `normal` and `stdBold` is used for `heading`:
```
fontsAlias:
    stdFont: inconsolata
    stdBold: carlito

styles:
    normal:
        textColor: #383745
        fontSize: 16
        alignment: TA_LEFT

    heading:
        fontSize: 32
        textColor: #1a8099

    heading1:
        parent: heading
        fontSize: 26
```

2. Using `fontName` to override the font works for `normal` and `heading1` styles, but **doesn't** work for the `heading` style, it keeps using the `stdBold` font (I also tested each case separately):
```
fontsAlias:
    stdFont: inconsolata
    stdBold: carlito

styles:
    normal:
        fontName: carlito
        textColor: #383745
        fontSize: 16
        alignment: TA_LEFT

    heading:
        fontName: inconsolata
        fontSize: 32
        textColor: #1a8099

    heading1:
        parent: heading
        fontName: inconsolata
        fontSize: 26
```
This is very weird since `heading1` has `heading` as its parent. Maybe `heading` is hardcoding the `stdBold` font?

3. Using `fontName: stdBold` in the `heading` style doesn't change anything, which is expected.

4. Setting `fontName` to `stdFont` for `heading` makes the `normal` style use the `stdBold` font (!?):
```
fontsAlias:
    stdFont: inconsolata
    stdBold: carlito

styles:
    normal:
        fontName: inconsolata
        textColor: #383745
        fontSize: 16
        alignment: TA_LEFT

    heading:
        fontName: stdFont
        fontSize: 32
        textColor: #1a8099

    heading1:
        parent: heading
        fontSize: 26

```
But that only happens if `normal` has `fontName: inconsolata`. When this is removed,  the `normal` style correctly uses `stdFont`, even though this line shouldn't have any effect.

Using `fontName: stdFont` in the `normal` style, also makes it use the `stdBold` font, but it also shouldn't change anything.

I hope this helps to debug. I can't dive into the code right now, but I will when I have the time.

**Comment by lornajane** [comment]
Thanks! I was doing something similar with the examples today (trying to debug something completely different) and I can replicate this: if I manually replace `stdFont` with whatever it was supposed to be aliased to, everything works.

**Comment by lornajane** [comment]
Ohhhh. I think the idea is that `stdFont` and `stdBold` are aware of one another, and are somehow expected to be different weights of the same loaded font. If I name my `stdFont` something else, such as `myFont`- everything works as I expected and `stdBold` stays independent of `myFont`.  There is more to do here I think to understand and document how the fonts relate to one another. I'd like to leave this issue open for longer and until we have a better handle on this.

**Comment by akrabat** [comment]
For item `2`: I think that the thing you are missing is that the style name for the title in the document is not `heading`, it's `title`.  `title` is defined in the default stylesheet with `fontName: stdBold` so changing the font in `heading` will not affect it.

You can get the default stylesheet by using: `rst2pdf  --print-stylesheet > default.style`

Item `4` is a bit weirder and is a bug. Looking in `styles.py`, when you set `fontName: stdFont` in `heading:`, the procession is such that the list in `fontsAlias` changes: 

before dealing with `fontName: stdFont` in `heading`:
```
{
    "stdFont": "inconsolata",
    "stdBold": "cardo",
    "stdItalic": "Helvetica-Oblique",
    "stdBoldItalic": "Helvetica-BoldOblique",
    "stdSans": "Helvetica",
    "stdSansBold": "Helvetica-Bold",
    "stdSansItalic": "Helvetica-Oblique",
    "stdSansBoldItalic": "Helvetica-BoldOblique",
    "stdMono": "Courier",
    "stdMonoItalic": "Courier-Oblique",
    "stdMonoBold": "Courier-Bold",
    "stdMonoBoldItalic": "Courier-BoldOblique",
    "stdSerif": "Times-Roman",
    "inconsolata": "Inconsolata-Regular_9ba2497f55c3435c544f6702d57e7a94",
    "inconsolata-Bold": "Inconsolata-Regular_9ba2497f55c3435c544f6702d57e7a94",
    "inconsolata-Oblique": "Inconsolata-Regular_9ba2497f55c3435c544f6702d57e7a94",
    "inconsolata-BoldOblique": "Inconsolata-Regular_9ba2497f55c3435c544f6702d57e7a94",
    "cardo": "Cardo-Regular",
    "cardo-Bold": "Cardo-Bold",
    "cardo-Oblique": "Cardo-Italic",
    "cardo-BoldOblique": "Cardo-Regular"
}
```

after dealing with `fontName: stdFont` in `heading`:

```
{
    "stdFont": "inconsolata",
    "stdBold": "cardo",
    "stdItalic": "Helvetica-Oblique",
    "stdBoldItalic": "Helvetica-BoldOblique",
    "stdSans": "Helvetica",
    "stdSansBold": "Helvetica-Bold",
    "stdSansItalic": "Helvetica-Oblique",
    "stdSansBoldItalic": "Helvetica-BoldOblique",
    "stdMono": "Courier",
    "stdMonoItalic": "Courier-Oblique",
    "stdMonoBold": "Courier-Bold",
    "stdMonoBoldItalic": "Courier-BoldOblique",
    "stdSerif": "Times-Roman",
    "inconsolata": "Cardo-Regular",
    "inconsolata-Bold": "Cardo-Bold",
    "inconsolata-Oblique": "Cardo-Italic",
    "inconsolata-BoldOblique": "Cardo-Regular",
    "cardo": "Cardo-Regular",
    "cardo-Bold": "Cardo-Bold",
    "cardo-Oblique": "Cardo-Italic",
    "cardo-BoldOblique": "Cardo-Regular"
}
```

As you can see, the references for the inconsolata font have been changed to cardo!

This is because of a variable called `fontList` that doesn't seem to get set every time around the loop if the font name is already in the list of embedded fonts. 

I'm pretty sure that the fix is to add `fontList = findfonts.autoEmbed(style[key])` before the [`pass` on line 366](https://github.com/rst2pdf/rst2pdf/blob/495c0974012694eac89b914617db173d5c2718de/rst2pdf/styles.py#L366).

I'll raised a PR once I've written a test for this and worked out why a load of sphinx tests break with this change, but I have to do the day-job first…

**Comment by nfraprado** [comment]
> For item `2`: I think that the thing you are missing is that the style name for the title in the document is not `heading`, it's `title`. `title` is defined in the default stylesheet with `fontName: stdBold` so changing the font in `heading` will not affect it.
> 
> You can get the default stylesheet by using: `rst2pdf --print-stylesheet > default.style`

Oh, now I get it. `heading` is the parent of `title`, but `title` defines its `fontName` as `stdBold`, so that's why changing `textColor` in `heading` affects it but changing `fontName` doesn't. But that still doesn't make sense for `fontSize`, since changing it in `heading` affects `title`'s size, even though it has `fontSize: 200%` in the default style...

> As you can see, the references for the inconsolata font have been changed to cardo!
> 
> This is because of a variable called `fontList` that doesn't seem to get set every time around the loop if the font name is already in the list of embedded fonts.
> 
> I'm pretty sure that the fix is to add `fontList = findfonts.autoEmbed(style[key])` before the [`pass` on line 366](https://github.com/rst2pdf/rst2pdf/blob/495c0974012694eac89b914617db173d5c2718de/rst2pdf/styles.py#L366).
> 
> I'll raised a PR once I've written a test for this and worked out why a load of sphinx tests break with this change, but I have to do the day-job first…

Nice catch, thanks for looking into it.

**Comment by nfraprado** [comment]
@akrabat I tested the fix in #911 and it does fix the weird behavior in `4`.

That said, it seems that the alias still doesn't work. That is, this works:
```
fontsAlias:
    stdFont: inconsolata
    stdBold: carlito

styles:
    normal:
        textColor: #383745
        fontSize: 16
        alignment: TA_LEFT

    heading:
        fontSize: 32
        textColor: #1a8099

    heading1:
        parent: heading
        fontName: inconsolata
        fontSize: 26
```

But changing `fontName: inconsolata` in `heading1` to `fontName: stdFont` *doesn't*. `heading1` keeps using `stdBold`.
Using `fontName: stdFont` in `normal` which shouldn't change anything, also makes it use `stdBold`, so it seems that issue is that all aliases are pointing to the last alias defined.

**Comment by akrabat** [comment]
> But changing `fontName: inconsolata` in `heading1` to `fontName: stdFont` _doesn't_. `heading1` keeps using `stdBold`.
> Using `fontName: stdFont` in `normal` which shouldn't change anything also makes it use `stdBold`, so it seems that the issue is that all aliases are pointing to the last alias defined.

With the #911 branch (`fix-fontlist-with-embedded-key-reference`), I don't see this.

That is, I did this:

```
fontsAlias:
    stdFont: inconsolata
    stdBold: cardo

styles:
    normal:
        textColor: #383745
        fontSize: 16
        alignment: TA_LEFT

    heading:
        fontSize: 32
        textColor: #1a8099

    heading1:
        parent: heading
        fontName: stdFont
        fontSize: 26
```

I see the title (_PDF Documents From Your Text Editor_) in Cardo, the body text in Inconsolata and the the heading 1 (_Further Sections, Headings, etc_) in Inconsolata.

If I use the `master` branch, then the heading 1 is in Cardo as you report. Can you double check please?
