### ISSUE TITLE
Space at the end of the slide creates empty slide when it doesn't fit

### ISSUE THREAD

**Issue by nfraprado** [rst2pdf/rst2pdf#921]
**Description of problem**

To vertically separate elements in a slide, rst2pdf inserts space before or after them (the amount of which can be configured in the style).
But if after the last element of the slide, the space doesn't fit, it will be put in the next slide, effectively creating an empty slide.

This is the desired behavior when the content doesn't fit a single slide, so it is continued in the next one, but I think that when the only thing to be carried to the next slide is just empty space, it should be suppressed, so this superfluous slide isn't created.

**What is the expected output? What do you see instead?**
As an example, I started with the basic presentation using the light theme, from the Examples page.
I downloaded the elephant image linked in that style and changed its size to reproduce the issue.

This is what it looks like when the image has width equal to `3.8cm`:
 
![width_3_8](https://user-images.githubusercontent.com/43095212/94153603-5c26aa80-fe53-11ea-867a-1fe805e94eb8.png)

Everything fits fine.
But then at `3.9cm`:
![width_3_9](https://user-images.githubusercontent.com/43095212/94153723-82e4e100-fe53-11ea-8730-c34e855ffc1f.png)

The additional space after the "Testing" text, used by rst2pdf as separation, doesn't fit and goes to the next slide, creating this empty slide.

And at `4.1cm`:
![width_4_1](https://user-images.githubusercontent.com/43095212/94153831-a27c0980-fe53-11ea-9f2c-b11bb533584b.png)

The "Testing" text also doesn't fit and is also bumped to the next slide. This is the desired behavior. The problem is between these two situations, when the only thing that doesn't fit is the empty space.

Fixing this would probably mean checking if the remainder of the slide content to be inserted in the pdf is just empty space, and if so, skipping it altogether.

🖥 **Versions**

`python -V`: Python 3.8.5

`pip freeze | grep rst2pdf`: -e git+git@github.com:nfraprado/rst2pdf.git@228411388f481ea32888b9a958f800f2be2450df#egg=rst2pdf
 (I'm following the master branch)

`pip freeze | grep reportlab`: reportlab==3.5.50

**Which operating system are you using?** Archlinux

**Comment by nfraprado** [comment]
I'm investigating this issue. It can be reproduced with the following:

command-line:
```
rst2pdf presentation1.rst -s light.style -b 1
```

rst:

```
An example presentation
#######################

.. class:: titleslideinfo

    generated by ``rst2pdf``

Image on a slide
================

.. Photo from https://www.flickr.com/photos/akrabat/6385577945 (Thanks @akrabat!)
.. image:: elephant.jpg
    :width: 3.0cm

Testing

Thank you
=========

Presentation strongly inspired by https://github.com/akrabat/rst2pdf_example_presentation
```

style:

```
pageSetup:
    size: null
    width: 16cm
    height: 9cm
    margin-top: 0cm
    margin-bottom: 0cm
    margin-left: 0cm
    margin-right: 0cm
    margin-gutter: 0cm
    spacing-header: 2mm
    spacing-footer: 2mm
    firstTemplate: standardPage

pageTemplates:
    standardPage:
        frames: []
            [3%, 3%, 94%, 94%]
        background: white.jpg
        showHeader: false
        showFooter: false

linkColor: #1b7b88

styles:
    normal:
        fontSize: 14

    bodytext:
        alignment: TA_LEFT
        hyphenation: false
        spaceAfter: 50

    titleslideinfo:
        parent: normal
        alignment: TA_CENTER

    literal:
        textColor: #000000

    code:
        parent: literal
        fontSize: 11
        leftIndent: 0
        spaceBefore: 8
        spaceAfter: 8
    image:
        spaceAfter: 50
```

The issue only happens when using the `-b` flag to break pages on headings (used for slides).

What seems to be happening is that a page gets full, so it goes to the next one. But then on this next one, the next thing is a heading, so it goes to the next page again, leaving one page blank.

Debugging I got to the following lines:

Whenever a heading is found in the rst, and it is below the break level, a page break is inserted before it:
https://github.com/rst2pdf/rst2pdf/blob/f1d5efe17db0ee15ade0ed54c1f4520e4b7992ec/rst2pdf/genelements.py#L242

When that page break is processed, it breaks the page, **but only if it isn't at the top of the page**:
https://github.com/rst2pdf/rst2pdf/blob/f1d5efe17db0ee15ade0ed54c1f4520e4b7992ec/rst2pdf/flowables.py#L449

So this conditional should be stopping this issue from happening. The fact that it isn't indicates either one of:
* The heading isn't actually at the top of the page because there is an invisible space before if from `spaceAfter` of the previous element. I initially thought this to be the case, but now I'm not so sure, since when executing the command line without the `-b`, the heading doesn't seem to be bumped down from this spacing. So I'm thinking rst2pdf/reportlab is suppressing the spacing when the page breaks, which is indeed the correct behavior. But that leaves...
* There's some bug in reportlab or in rst2pdf's usage of reportlab that is causing the frame's `_atTop` to not be set on the page break, like it should, making rst2pdf think that the heading isn't at the top of the page when it is, so the page is broken twice, leaving a blank page.

That's as far as I've gotten. If anyone knows a way to print all the elements on each pdf page as it is generated by rst2pdf, that would be really useful to really eliminate the first option.
